// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: service_simple_bank.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MSMBank_CreateUser_FullMethodName = "/pb.MSMBank/CreateUser"
	MSMBank_LoginUser_FullMethodName  = "/pb.MSMBank/LoginUser"
)

// MSMBankClient is the client API for MSMBank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MSMBankClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserRes, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserRes, error)
}

type mSMBankClient struct {
	cc grpc.ClientConnInterface
}

func NewMSMBankClient(cc grpc.ClientConnInterface) MSMBankClient {
	return &mSMBankClient{cc}
}

func (c *mSMBankClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserRes, error) {
	out := new(CreateUserRes)
	err := c.cc.Invoke(ctx, MSMBank_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mSMBankClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserRes, error) {
	out := new(LoginUserRes)
	err := c.cc.Invoke(ctx, MSMBank_LoginUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MSMBankServer is the server API for MSMBank service.
// All implementations must embed UnimplementedMSMBankServer
// for forward compatibility
type MSMBankServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserRes, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserRes, error)
	mustEmbedUnimplementedMSMBankServer()
}

// UnimplementedMSMBankServer must be embedded to have forward compatible implementations.
type UnimplementedMSMBankServer struct {
}

func (UnimplementedMSMBankServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMSMBankServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedMSMBankServer) mustEmbedUnimplementedMSMBankServer() {}

// UnsafeMSMBankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MSMBankServer will
// result in compilation errors.
type UnsafeMSMBankServer interface {
	mustEmbedUnimplementedMSMBankServer()
}

func RegisterMSMBankServer(s grpc.ServiceRegistrar, srv MSMBankServer) {
	s.RegisterService(&MSMBank_ServiceDesc, srv)
}

func _MSMBank_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSMBankServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MSMBank_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSMBankServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MSMBank_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MSMBankServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MSMBank_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MSMBankServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MSMBank_ServiceDesc is the grpc.ServiceDesc for MSMBank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MSMBank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MSMBank",
	HandlerType: (*MSMBankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _MSMBank_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _MSMBank_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_simple_bank.proto",
}
